### ISSUE TITLE
Issue that stops map donwloading

### ISSUE THREAD

**Issue by AMERICANNEWSGMS** [StrangeOne101/PlatinumArenas#22]
error
[21:10:39 WARN]: [PlatinumArenas] Task #18481 for PlatinumArenas v0.8.0 generated an exception
java.lang.ClassCastException: class net.minecraft.world.item.component.ResolvableProfile cannot be cast to class com.mojang.authlib.GameProfile (net.minecraft.world.item.component.ResolvableProfile and com.mojang.authlib.GameProfile are in unnamed module of loader java.net.URLClassLoader @41cf53f9)
	at PlatinumArenas-0.8.0.jar/com.strangeone101.platinumarenas.blockentity.SkullWrapper.cache(SkullWrapper.java:57) ~[PlatinumArenas-0.8.0.jar:?]
	at PlatinumArenas-0.8.0.jar/com.strangeone101.platinumarenas.blockentity.SkullWrapper.cache(SkullWrapper.java:16) ~[PlatinumArenas-0.8.0.jar:?]
	at PlatinumArenas-0.8.0.jar/com.strangeone101.platinumarenas.Arena.loopyCreate(Arena.java:643) ~[PlatinumArenas-0.8.0.jar:?]
	at PlatinumArenas-0.8.0.jar/com.strangeone101.platinumarenas.Arena$3.run(Arena.java:665) ~[PlatinumArenas-0.8.0.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1804) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1665) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1330) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

it keeps stopping at around 29%

<img width="561" alt="Screenshot 2024-12-23 at 3 15 06 PM" src="https://github.com/user-attachments/assets/938f48f6-80e5-491e-9641-c607ec1c1b79" />

**Comment by StrangeOne101** [comment]
Thanks for the report. Looking into it now

**Comment by AMERICANNEWSGMS** [comment]
Hey I know you jsut responded an hour ago. But if you have found the error do you know when the next fix/update will be?

**Comment by StrangeOne101** [comment]
I'll unfortunately only be able to fix it post Christmas, sorry. 

I took a brief look into the issue. And seems that paper broke a whole lot more in the recent update than just that

**Comment by AMERICANNEWSGMS** [comment]
Ok thanks. Your plugin is amazing and i can understand that it may require a lot of maintenance. Merry Christmas!

**Comment by StrangeOne101** [comment]
Update: I'm still working on this. With the way it broke, I'd either have to
1. Make the plugin ONLY for 1.21
2. Take some time to implement some proper multi version support

I'm currently doing 2, but it is taking longer than expected. If it isn't done by today, I'll put out a pre-release on GitHub JUST for 1.21

**Comment by StrangeOne101** [comment]
Can you confirm it is fixed? https://github.com/StrangeOne101/PlatinumArenas/releases/tag/v0.8.1

**Comment by AMERICANNEWSGMS** [comment]
sorry for the late response. I will try first thing tommorw. I am not in town for my pc but will check soon

**Comment by AMERICANNEWSGMS** [comment]
Ok yes it works now! Thanks
